language: python

python:
  - "2.7"

install:
  - wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2 || wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2
  - tar -xjf default.tar.bz2
  - mv pypy-pypy-* pypy
# command to run tests
script: PYTHONPATH=$PYTHONPATH:pypy nosetests
