language: python

python:
  - "2.7"
  - "pypy"

env:
  global:
    - PYTHONPATH=$PYTHONPATH:pypy:src
  matrix:
    - RUN=hosted
    - RUN=translated OPTIMIZE=2
    - RUN=translated OPTIMIZE=jit

before_install:
  - git submodule update --init --recursive

install:
  - wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2 || wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2
  - tar -xjf default.tar.bz2
  - mv pypy-pypy-* pypy

script: tests/travis.sh
